import "./globals.css";

import { Inter, Delius } from "next/font/google";
import Header from "./header";
import { cn } from "@/lib/utils";
import { AppProviders } from "./providers";

const inter = Inter({ subsets: ["latin"] });
const fdrika = Delius({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "InferAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          `${inter.className} max-w-[1200px] mx-auto w-screen h-screen dark`
          // `[--handwritten:${fdrika.style.fontFamily}]`
        )}
        style={{
          ["--handwritten"]: fdrika.style.fontFamily,
        }}
      >
        <AppProviders>
          <Header />
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
